### ISSUE TITLE
Instructions for using the Docker image

### ISSUE THREAD

**Issue by moldach** [zlskidmore/docker-picard#2]
I'm trying to use with image in a Snakemake rule but I'm not sure how to call `Picard`'s `AddOrReplaceReadGroups` function?

```
rule add_RG_to_razers3:
                input:
                        reads=lambda wildcards: getTmpBams(wildcards.sample),
                output:
                        os.path.join(dirs_dict["ALIGN_DIR"],config["ALIGN_TOOL"],"{sample}.bam")
                threads: 1
                resources:
                        mem=200,
                        time=5
                params:
                        sample="{sample}"
                container:
                        "docker://zlskidmore/picard:2.22.9"
                shell: """
               java -jar /usr/local/bin/picard/picard.jar AddOrReplaceReadGroups I={input} O={output} RGID={params.sample} RGLB=lib1 RGPL=ILLUMINA RGSM={params.sample} RGPU=unit1
                """
```

I get the following error:

```
Activating singularity image /home/moldach/projects/def-mtarailo/common/snakemake_cache/singularity_images/e56d2444db8faf79c3c3fb9de709687d.simg
INFO    2020-10-01 17:04:59     AddOrReplaceReadGroups

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    AddOrReplaceReadGroups -I alignment/razers3/tmp/MTG324.bam -O alignment/razers3/MTG324.bam -RGID MTG324 -RGLB lib1 -RGPL ILLUMINA -RGSM MTG324 -RGPU unit1
**********


17:05:00.653 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/bin/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Oct 01 17:05:00 GMT 2020] AddOrReplaceReadGroups INPUT=alignment/razers3/tmp/MTG324.bam OUTPUT=alignment/razers3/MTG324.bam RGID=MTG324 RGLB=lib1 RGPL=ILLUMINA RGPU=unit1 RGSM=MTG324    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Oct 01 17:05:00 GMT 2020] Executing as moldach@cdr752.int.cedar.computecanada.ca on Linux 3.10.0-1062.12.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_252-8u252-b09-1~18.04-b09; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.22.9
INFO    2020-10-01 17:05:00     AddOrReplaceReadGroups  Created read-group ID=MTG324 PL=ILLUMINA LB=lib1 SM=MTG324

[Thu Oct 01 17:05:00 GMT 2020] picard.sam.AddOrReplaceReadGroups done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2041446400
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///scratch/moldach/MTG-workflows/alignment/razers3/MTG324.bam. Sort order is coordinate. Offending records are at [I:219] and [I:180]
        at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:197)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:184)
        at picard.sam.AddOrReplaceReadGroups.doWork(AddOrReplaceReadGroups.java:184)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
[Thu Oct  1 10:05:01 2020]
Error in rule add_RG_to_razers3:
    jobid: 0
    output: alignment/razers3/MTG324.bam
    shell:

                java -jar /usr/local/bin/picard/picard.jar AddOrReplaceReadGroups I=alignment/razers3/tmp/MTG324.bam O=alignment/razers3/MTG324.bam RGID=MTG324 RGLB=lib1 RGPL=ILLUMINA RGSM=MTG324 RGPU=unit1

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job add_RG_to_razers3 since they might be corrupted:
alignment/razers3/MTG324.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by vdauwera** [comment]
Hi, you need to rewrite the command using the new CLI syntax. See the documentation linked in the error message for details. The error message even suggests what the new version of your command should probably be (but make sure to check just in case it didn’t get interpreted perfectly).

**Comment by yfarjoun** [comment]
I suspect that the input file is corrupted. can you see if it validates with ValidateSamFile? I think that its header claims an order that isn't satisfied by the contents of the file.

**Comment by moldach** [comment]
The problem was the file needed to be sorted first
